#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','c','c',' ','-','I','.',' ','-',
        'I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',' ',
        '-','D','O','P','E','N','S','S','L','_','T','H','R','E','A','D','S',' ',
        '-','D','_','R','E','E','N','T','R','A','N','T',' ','-','D','D','S','O',
        '_','D','L','F','C','N',' ','-','D','H','A','V','E','_','D','L','F','C',
        'N','_','H',' ','-','a','r','c','h',' ','x','8','6','_','6','4',' ','-',
        'O','3',' ','-','D','L','_','E','N','D','I','A','N',' ','-','W','a','l',
        'l','\0'
    };
    #define PLATFORM "platform: darwin64-x86_64-cc"
    #define DATE "built on: Mon Oct 24 12:52:55 2016"
#endif
